# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kratix < Formula
  desc "CLI-based tool to build Promises"
  homepage "https://docs.kratix.io/main/kratix-cli/intro"
  version "0.18.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/syntasso/kratix-cli/releases/download/v0.18.0/kratix-cli_Darwin_x86_64.tar.gz"
      sha256 "6a995f00bb1165cd9c8984faf92fdc93563bbe5dff6234a736c571a99454f8da"

      def install
        bin.install "kratix"
      end
    end
    on_arm do
      url "https://github.com/syntasso/kratix-cli/releases/download/v0.18.0/kratix-cli_Darwin_arm64.tar.gz"
      sha256 "09a8b506bcaa75b8a2849b4eeec501894966032a2df62483f1c8f9c9b653a34d"

      def install
        bin.install "kratix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/syntasso/kratix-cli/releases/download/v0.18.0/kratix-cli_Linux_x86_64.tar.gz"
        sha256 "a51968eaeb5e431f1345b6dd9e1a696e06202f459c741edef452ef5f4920b5d2"

        def install
          bin.install "kratix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/syntasso/kratix-cli/releases/download/v0.18.0/kratix-cli_Linux_arm64.tar.gz"
        sha256 "688ff78c4f407ec23f0f7439824ef65c9a43305f345370f7992a4a9f246132d3"

        def install
          bin.install "kratix"
        end
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kratix --version")
  end
end
